---
version: "3.9"

services:
  mariadb:
    container_name: marrria
    hostname: marrria
    build: requirements/mariadb
    networks:
      - incepnet

  nginx:
    container_name: nemo
    hostname: nemo
    build: requirements/nginx
    ports:
      - 80:80
    networks:
      - incepnet

  wordpress:
    container_name: philippe
    hostname: philippe
    build: requirements/wordpress
    networks:
      - incepnet
    volumes:
      - website:/wordpress

networks:
  incepnet:
    driver: bridge
    name: incepnet
    ipam:
      driver: default
      config:
        - subnet: 172.42.0.0/29
          gateway: 172.42.0.1
    internal: false
    attachable: false

volumes:
  website:
    driver: local
    name: website

...
