---
version: "3.9"

services:
  mariadb:
    container_name: ${CONTAINER_MARIADB}
    image: ${IMAGE_MARIADB}
    hostname: inception-container-mariadb
    build: requirements/mariadb
    networks:
      - incepnet
    volumes:
      - basedata:/var/lib/mysql
    environment:
      - CONTAINER_WORDPRESS=${CONTAINER_WORDPRESS}
      - DATABASE_DATABASE=${DATABASE_DATABASE}
      - DATABASE_USER_NAME=${DATABASE_USER_NAME}
      - DATABASE_USER_PASSWORD=${DATABASE_USER_PASSWORD}
      - DATABASE_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}

  nginx:
    container_name: ${CONTAINER_NGINX}
    image: ${IMAGE_NGINX}
    hostname: inception-container-nginx
    build: requirements/nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - incepnet
    volumes:
      - website:/wordpress
    environment:
      - CONTAINER_WORDPRESS=${CONTAINER_WORDPRESS}
      - DOMAIN_NAME=${DOMAIN_NAME}

  wordpress:
    container_name: ${CONTAINER_WORDPRESS}
    image: ${IMAGE_WORDPRESS}
    hostname: inception-container-wordpress
    build: requirements/wordpress
    networks:
      - incepnet
    volumes:
      - website:/wordpress
    environment:
      - CONTAINER_MARIADB=${CONTAINER_MARIADB}
      - DATABASE_DATABASE=${DATABASE_DATABASE}
      - DATABASE_USER_NAME=${DATABASE_USER_NAME}
      - DATABASE_USER_PASSWORD=${DATABASE_USER_PASSWORD}
      - WORDPRESS_ADMIN=${WORDPRESS_ADMIN}
      - WORDPRESS_MAIL=${WORDPRESS_MAIL}
      - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}
      - WORDPRESS_URL=${WORDPRESS_URL}

networks:
  incepnet:
    driver: bridge
    name: incepnet
    ipam:
      driver: default
      config:
        - subnet: 172.42.0.0/29
          gateway: 172.42.0.1
    internal: false
    attachable: false

volumes:
  website:
    driver: local
    name: website
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/wordpress'

  basedata:
    driver: local
    name: basedata
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/mysql'
...
