---
version: "3.9"

services:
  mariadb:
    container_name: inception-container-mariadb
    image: inception-image-mariadb
    hostname: inception-container-mariadb
    build: requirements/mariadb
    networks:
      - incepnet
    volumes:
      - basedata:/var/lib/mysql
    environment:
      - DATABASE_DATABASE=${DATABASE_DATABASE}
      - DATABASE_USER_NAME=${DATABASE_USER_NAME}
      - DATABASE_USER_PASSWORD=${DATABASE_USER_PASSWORD}
      - DATABASE_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}

  nginx:
    container_name: inception-container-nginx
    image: inception-image-nginx
    hostname: inception-container-nginx
    build: requirements/nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - incepnet
    volumes:
      - website:/wordpress

  wordpress:
    container_name: inception-container-wordpress
    image: inception-image-wordpress
    hostname: inception-container-wordpress
    build: requirements/wordpress
    networks:
      - incepnet
    volumes:
      - website:/wordpress
    environment:
      - DATABASE_DATABASE=${DATABASE_DATABASE}
      - DATABASE_USER_NAME=${DATABASE_USER_NAME}
      - DATABASE_USER_PASSWORD=${DATABASE_USER_PASSWORD}
      - WORDPRESS_ADMIN=${WORDPRESS_ADMIN}
      - WORDPRESS_MAIL=${WORDPRESS_MAIL}
      - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}
      - WORDPRESS_URL=${WORDPRESS_URL}

networks:
  incepnet:
    driver: bridge
    name: incepnet
    ipam:
      driver: default
      config:
        - subnet: 172.42.0.0/29
          gateway: 172.42.0.1
    internal: false
    attachable: false

volumes:
  website:
    driver: local
    name: website

  basedata:
    driver: local
    name: basedata
...
