---
services:
  mariadb:
    container_name: marrria
    hostname: marrria
    build: requirements/mariadb
    networks:
      - incepnet

  nginx:
    container_name: nemo
    hostname: nemo
    build: requirements/nginx
    ports:
      - 80:80
    networks:
      - incepnet

networks:
  incepnet:
    driver: bridge
    name: incepnet
    ipam:
      driver: default
      config:
        - subnet: 172.42.0.0/29
          gateway: 172.42.0.1
    internal: false
    attachable: false
...
