= Docker
:nofooter:
:toc: left

== Deployment

[plantuml, target=assets/deployment, format=svg, width=100%]
....
rectangle computer {
	rectangle "virtual machine" as vm {
		rectangle "docker network" as dnetwork {
			component "docker\nnginx" as dnginx
			component "docker\nmariadb" as dmariadb
			component "docker\nphp/wordpress" as dwordpress
		}
		database website
		database database
		component ".env" as envfile
		component "docker-compose.yaml" as dockercompose
	}
}

website -- dwordpress
website -- dnginx

database -- dmariadb

dmariadb -- dwordpress
dnginx -- dwordpress

computer --> vm : ssh user@ip -L 8080:localhost:80
....

== SSL

[plantuml, target=assets/ssl, format=svg, width=100%]
....
client -> website : request on port 443
website -> client : give his public key
note left
create a random symmetric key
cipher the symmetric key with the server public key
end note
client -> website : send the crypted symmetric key
note over website, client
the communication is ciphered by the symmetric key
end note
....
